# Generated by Django 5.2.1 on 2025-05-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0002_address_city_state_profile_favorites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='closing_time',
            new_name='application_time',
        ),
        migrations.RemoveField(
            model_name='address',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='address',
            name='opening_time',
        ),
    ]
