# Generated by Django 5.2.1 on 2025-05-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0007_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Rua, nº, freguesia, Código Postal'),
        ),
    ]
