# Generated by Django 5.2.1 on 2025-05-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0008_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_informations',
            field=models.TextField(default='Descreva sobre o seu atual quadro de obesidade, quais as medicações que faz uso e se possui outras doenças crônicas'),
        ),
    ]
