# Generated by Django 5.2.1 on 2025-05-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0009_profile_bio_profile_health_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estado_civil',
            field=models.IntegerField(default=0),
        ),
    ]
