# Generated by Django 5.2.1 on 2025-05-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0010_profile_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='estado_civil',
            field=models.IntegerField(default=3),
        ),
    ]
