# Generated by Django 5.2.1 on 2025-05-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0011_alter_profile_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='estado_civil',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Usuário')], default=3),
        ),
    ]
