# Generated by Django 5.2.1 on 2025-05-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0012_alter_profile_estado_civil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='estado_civil',
        ),
        migrations.AddField(
            model_name='profile',
            name='civil_status',
            field=models.IntegerField(choices=[(1, 'Solteiro(a)'), (2, 'Casado(a)'), (3, 'União estável'), (4, 'Divorciado(a)'), (5, 'Viúvo(a)')], default=5),
        ),
    ]
