# Generated by Django 5.2.1 on 2025-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0013_remove_profile_estado_civil_profile_civil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.IntegerField(choices=[(1, 'Fundamental 9º ano'), (2, 'Ensino Secundário, 12º ano'), (3, 'Graduação'), (4, 'Pós-graduação')], default=4),
        ),
    ]
