# Generated by Django 5.2.1 on 2025-05-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0014_profile_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
    ]
