# Generated by Django 5.2.1 on 2025-05-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0017_user_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
